import React from 'react';

export function About() {
  return (
    <div className="container">
      <h2>Karaoke Club</h2>
      <p>aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfaaofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfaaofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfaaofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfaaofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfaaofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfaaofdjaowiefoawehnfo
        aiwehfoaiwehfoaiwhefoiawheo
        fihawoiehfaaofdjaowiefoawehnfoaiw
        ehfoaiwehfoaiwhefoiawheofihawoiehfaa
        ofdjaowiefoawehnfoaiwehfoaiwehfoaiwhe
        foiawheofihawoiehfaaofdjaowiefoawehnfoa
        iwehfoaiwehfoaiwhefoiawheofihawoiehfaao
        fdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoi
        awheofihawoiehfaaofdjaowiefoawehnfoaiweh
        foaiwehfoaiwhefoiawheofihawoiehfaaofdjao
        wiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofi
        hawoiehfaaofdjaowiefoawehnfoaiwehfoaiwehf
        oaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        aofdjaowiefoawehnfoaiwehfoaiwehfoaiwhefoiawheofihawoiehfa
        </p>
    </div>
  );
}
